### ISSUE TITLE
Fragment Edit/Add Item

### ISSUE THREAD

**Issue by PassiDel** [WeFridge/WeFridge#12]
Design from Figma

**Comment by henrijaeger** [comment]
With the commits of today in feature/fragment_item_edit_add, our app now supports synchronization with Firestore.
During the development, one problem has arised:
How can I access the contactEmail / contactName, so that this information is saved into the Item object? Those values are stored somewhere locally on the device, right? @PassiDel can you help me with that?

Note: Since our Firestore rules changed, I currently cannot fetch any data from Firestore ("posting" data still works).
@AlexTerhar  @frcroth @PassiDel: Could you take a look at that? The 'getItems' method in the ItemController is responsible for building this query.

**Comment by PassiDel** [comment]
The contact info is stored in the SharedPreferences, take a look at the [SettingsFragment](https://github.com/WeFridge/WeFridge/blob/main/app/src/main/java/app/wefridge/wefridge/SettingsFragment.kt#L46-L62)

The FirebaseAuth information is used as a fallback value:
```kt
val sp = PreferenceManager.getDefaultSharedPreferences(context)

val user = FirebaseAuth.getInstance().currentUser!!

email = sp.getString(SETTINGS_EMAIL, user.email!!)!!
name = sp.getString(SETTINGS_NAME, user.displayName!!)!!
```

The reference to the Preferences (`PreferenceManager.getDefaultSharedPreferences(context)`) can be fetch once on startup. but the data should be fetched (`sp.getString(...)`) regularly, to respect updates on the settings fragment.
